### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

### ISSUE THREAD

**Issue by richkidpe** [aaguiar10/gflows#2]
Thanks for sharing but I find this error, despite doing all the correct steps.

**Comment by richkidpe** [comment]
![plop](https://github.com/aaguiar10/gflows/assets/143129152/bab4317a-eb49-4247-aa7f-eca67eb091b3)

**Comment by aaguiar10** [comment]
> Thanks for sharing but I find this error, despite doing all the correct steps.

Hi @richkidpe,
This error happens because the scheduler uses the dwn_data function to request data from an API. Within the `ticker_dwn` module this function is looking for an API_URL environment variable to use in the request.

Commenting out these lines in `my_app.py` should get it running without needing a valid API_URL
```
sched = BackgroundScheduler(daemon=True)
# sched.add_job(sensor)
# sched.add_job(sensor, CronTrigger.from_crontab("0,30 13-20 * * 0-4", timezone=UTC))
sched.start()
```

**Comment by aaguiar10** [comment]
> Thanks for sharing but I find this error, despite doing all the correct steps.

Hi @richkidpe,

This error happens because the app's scheduler uses the dwn_data function to request data from an API. Within the `ticker_dwn` module this function is looking for an API_URL environment variable to use in the request.

Commenting out these lines in `my_app.py` should get it running without needing a valid API_URL
```
# sched.add_job(sensor)
# sched.add_job(sensor, CronTrigger.from_crontab("0,30 13-20 * * 0-4", timezone=UTC))
```

**Comment by richkidpe** [comment]
Thank you for responding. It worked, but it seems there might be issues with loading the CSV data.

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'my_app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
127.0.0.1 - - [26/Aug/2023 16:21:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:45] "GET /assets/style.css?m=1692576336.0 HTTP/1.1" 304 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_favicon.ico?v=2.9.3 HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /assets/cup.webp HTTP/1.1" 304 -
127.0.0.1 - - [26/Aug/2023 16:21:46] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 304 -
[2023-08-26 16:21:47,114] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\dash\dash.py", line 1283, in dispatch
    ctx.run(
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\dash\_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\Desktop\gflows-main\gflows-main\my_app.py", line 193, in update_live_chart
    ) = query_data(stock, expiration)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 877, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_caching\__init__.py", line 180, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\Desktop\gflows-main\gflows-main\my_app.py", line 53, in query_data
    result = getOptionsData(ticker, expir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Richkidpe 3\Desktop\gflows-main\gflows-main\calc.py", line 138, in getOptionsData
    retrieved_ampm = todayDate[1].split("at")[1].split("EDT")
                     ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
127.0.0.1 - - [26/Aug/2023 16:21:47] "POST /_dash-update-component HTTP/1.1" 500 -

**Comment by aaguiar10** [comment]
You're welcome! 

@richkidpe can you share the first few lines of your CSV data? The other error is related to the "Date:" string that's pulled from the 3rd line.

**Comment by richkidpe** [comment]
Standard & Poors 500 Index,Last: 4405.71,Change:  29.4
"Date: 27 de agosto de 2023, 13:35 GMT-4",Bid: 4372.4199,Ask: 4424.3501,Size: 1*1,Volume: 0
Expiration Date,Calls,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest,Strike,Puts,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest
Fri Aug 25 2023,SPXW230825C04395000,9.03,-5.22,7.7,15.4,27417,0,0,0,1586,4395.00,SPXW230825P04395000,0.05,-23.6,0,0.05,31015,0,0,0,2541
Fri Aug 25 2023,SPXW230825C04400000,6,-6.2,5,6.5,72569,0,0,0,8113,4400.00,SPXW230825P04400000,0.05,-26.5,0,0.05,53405,0,0,0,7909
Fri Aug 25 2023,SPXW230825C04405000,0.4,-9.95,0.25,1.05,46167,0,0,0,1516,4405.00,SPXW230825P04405000,0.4,-29.25,0.3,0.45,34501,0,0,0,1394
Fri Aug 25 2023,SPXW230825C04410000,0.05,-8.6,0,0.05,69650,0,0,0,1552,4410.00,SPXW230825P04410000,4.3,-28.9,4,5,29282,0,0,0,1547
Fri Aug 25 2023,SPXW230825C04415000,0.05,-7.15,0,0.05,65938,0,0,0,2546,4415.00,SPXW230825P04415000,9.6,-26.9,8.8,10.7,15668,0,0,0,1013
Fri Aug 25 2023,SPXW230825C04420000,0.05,-5.85,0,0.05,71006,0,0,0,5770,4420.00,SPXW230825P04420000,15.3,-24.9,9.5,17,7682,0,0,0,1187
Mon Aug 28 2023,SPXW230828C04395000,20.4,0.5,21,21.4,2782,0.0909,0.6164,0.0106,915,4395.00,SPXW230828P04395000,9.38,-20.15,8.8,9.1,3515,0.089,-0.3833,0.0106,511
Mon Aug 28 2023,SPXW230828C04400000,17.7,-0.7,17.9,18.2,5781,0.0895,0.563,0.0111,1243,4400.00,SPXW230828P04400000,10.95,-20.5,10.6,10.9,5528,0.088,-0.4367,0.0111,1419
Mon Aug 28 2023,SPXW230828C04405000,14.8,-1.5,15,15.3,3974,0.0886,0.5073,0.0113,721,4405.00,SPXW230828P04405000,13,-21.7,12.8,13.1,2212,0.0874,-0.4925,0.0113,441
Mon Aug 28 2023,SPXW230828C04410000,12.5,-1.9,12.5,12.7,4763,0.0882,0.4504,0.0114,363,4410.00,SPXW230828P04410000,15.59,-21.85,15.2,15.5,3245,0.0867,-0.5493,0.0114,776
Mon Aug 28 2023,SPXW230828C04415000,10.22,-2.18,10.2,10.4,4269,0.0875,0.3938,0.0111,423,4415.00,SPXW230828P04415000,18.5,-22.75,17.9,18.2,1535,0.086,-0.6059,0.0111,321
Mon Aug 28 2023,SPXW230828C04420000,8.2,-2.63,8.3,8.5,3630,0.0869,0.3391,0.0106,420,4420.00,SPXW230828P04420000,21.04,-23.51,20.9,21.3,1306,0.0857,-0.6606,0.0106,384
Tue Aug 29 2023,SPXW230829C04395000,26.4,2.05,26.7,27.1,355,0.11,0.5882,0.0077,102,4395.00,SPXW230829P04395000,14.85,-17.5,14.1,14.4,694,0.1085,-0.4115,0.0077,200
Tue Aug 29 2023,SPXW230829C04400000,23.6,1.7,23.8,24.1,1569,0.109,0.5497,0.0079,147,4400.00,SPXW230829P04400000,16.6,-18.8,16.1,16.4,1757,0.1078,-0.4501,0.0079,1606
Tue Aug 29 2023,SPXW230829C04405000,20.8,0.8,20.9,21.3,373,0.1086,0.51,0.008,74,4405.00,SPXW230829P04405000,18.6,-19.1,18.3,18.5,314,0.1069,-0.4897,0.008,348
Tue Aug 29 2023,SPXW230829C04410000,18.1,0.5,18.3,18.6,603,0.1074,0.4698,0.0081,104,4410.00,SPXW230829P04410000,21,-19.6,20.6,20.9,227,0.106,-0.5299,0.0081,190
Tue Aug 29 2023,SPXW230829C04415000,16.1,0.4,16,16.2,443,0.107,0.4293,0.008,140,4415.00,SPXW230829P04415000,24.07,-19.78,23.1,23.5,154,0.1053,-0.5704,0.008,99
Tue Aug 29 2023,SPXW230829C04420000,13.7,-0.2,13.7,14,673,0.106,0.3891,0.0079,117,4420.00,SPXW230829P04420000,26.87,-20.18,25.8,26.2,112,0.1046,-0.6106,0.0079,172
Wed Aug 30 2023,SPXW230830C04395000,32.65,5.25,30.9,31.4,227,0.1194,0.5732,0.0064,96,4395.00,SPXW230830P04395000,19.1,-16.45,18.3,18.6,221,0.1186,-0.4266,0.0064,611
Wed Aug 30 2023,SPXW230830C04400000,27.5,2.4,28,28.4,1261,0.1187,0.5413,0.0065,501,4400.00,SPXW230830P04400000,21.15,-17.15,20.4,20.7,1303,0.1174,-0.4584,0.0065,989
Wed Aug 30 2023,SPXW230830C04405000,25.3,2.25,25.2,25.6,249,0.1178,0.5087,0.0066,155,4405.00,SPXW230830P04405000,23.17,-17.88,22.6,22.9,328,0.1164,-0.491,0.0066,160
Wed Aug 30 2023,SPXW230830C04410000,22.4,1.85,22.5,22.9,443,0.1172,0.4757,0.0066,180,4410.00,SPXW230830P04410000,25.3,-18.6,24.9,25.2,377,0.1156,-0.524,0.0066,563
Wed Aug 30 2023,SPXW230830C04415000,20.7,2.1,20,20.4,252,0.116,0.4424,0.0066,125,4415.00,SPXW230830P04415000,28.25,-18.6,27.4,27.7,182,0.115,-0.5572,0.0066,549
Wed Aug 30 2023,SPXW230830C04420000,17.9,1.25,17.7,18.1,326,0.1153,0.4092,0.0066,144,4420.00,SPXW230830P04420000,31.3,-18.55,30,30.5,204,0.114,-0.5905,0.0065,181
Thu Aug 31 2023,SPXW230831C04395000,35.55,3.7,35.4,35.8,286,0.1256,0.5734,0.0056,293,4395.00,SPXW230831P04395000,23.2,-14.75,21.2,21.5,128,0.1241,-0.4268,0.0056,380
Thu Aug 31 2023,SPXW230831C04400000,32.2,3.7,32.5,32.8,2176,0.125,0.5457,0.0057,5944,4400.00,SPXW230831P04400000,23.96,-17.1,23.2,23.5,2500,0.1232,-0.4545,0.0057,9634
Thu Aug 31 2023,SPXW230831C04405000,30.6,3.06,29.6,30,395,0.124,0.5174,0.0057,86,4405.00,SPXW230831P04405000,26.43,-17.3,25.3,25.7,229,0.1225,-0.4828,0.0057,436
Thu Aug 31 2023,SPXW230831C04410000,26.6,2.4,26.9,27.3,335,0.123,0.4887,0.0058,626,4410.00,SPXW230831P04410000,28.78,-17.02,27.6,28,182,0.1215,-0.5115,0.0058,454
Thu Aug 31 2023,SPXW230831C04415000,25,2.95,24.3,24.7,164,0.122,0.4597,0.0058,274,4415.00,SPXW230831P04415000,30.9,-17.9,30,30.4,150,0.1208,-0.5405,0.0058,188
Thu Aug 31 2023,SPXW230831C04420000,23.01,2.96,21.9,22.2,384,0.1211,0.4306,0.0058,524,4420.00,SPXW230831P04420000,33.1,-18.65,32.6,33,111,0.1199,-0.5696,0.0058,517

**Comment by richkidpe** [comment]
![DATA CSV](https://github.com/aaguiar10/gflows/assets/143129152/12a62834-f163-45c9-a696-8cd5ebdf29af)

**Comment by aaguiar10** [comment]
Hi @richkidpe,

I've released an update that should fix the CSV issue. The `calc` module only supported the US/EU date formats so it would throw an error with other dates such as _2023年8月29日 GMT-4 22:40_ or, in your case, _27 de agosto de 2023_, 13:35 GMT-4. G|Flows will now be able to handle most formats, so let me know if the data loads correctly for you.

Thanks for bringing it to my attention

**Comment by rdyvptnm** [comment]
> ![plop](https://user-images.githubusercontent.com/143129152/263105704-bab4317a-eb49-4247-aa7f-eca67eb091b3.png)

I am also getting same error. Do i need to get the csv file from cboe or the one provided in data folder is good enough to pull the real time options

**Comment by aaguiar10** [comment]
@rdyvptnm 

The format that `calc.py` looks for is like the examples provided. Without an API, the quickest way to get a CSV file in this format is from the CBOE site.
```
  ---Example Data---
  Standard & Poors 500 Index,Last: 3990.5601,Change:  56.1801
  "Date: December 12, 2022 at 8:30 PM EST",Bid: 3962.01,Ask: 4016.6299,Size: 1*1,Volume: 0
  Expiration Date,Calls,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest,Strike,Puts,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest
  Mon Dec 12 2022,SPXW221212C01000000,2943.2,0.25,0,0,8,0,0,0,1,1000.00,SPXW221212P01000000,0,0,0,0,0,0,0,0,0
  ...
```
However, you can modify it to your preference. The spot price is taken from the 2nd line (1st line is ignored), and the date is taken from the 3rd.
```
  # Get Spot
  spotLine = optionsFileData[1]
  spotPrice = float(spotLine.split("Last:")[1].split(",")[0])
  fromStrike = 0.5 * spotPrice
  toStrike = 1.5 * spotPrice
  # Get Today's Date
  dateLine = optionsFileData[2]
  todayDate = dateLine.split("Date: ")[1].split(",Bid")[0]
```
The options data is separated in columns starting from the fifth line.
```
  df = pd.read_csv(filename, sep=",", header=None, skiprows=4)
  df.columns = [
      "ExpirationDate",
      "Calls",
      "CallLastSale",
      "CallNet",
      "CallBid",
      "CallAsk",
      "CallVol",
      "CallIV",
      "CallDelta",
      "CallGamma",
      "CallOpenInt",
      "StrikePrice",
      "Puts",
      "PutLastSale",
      "PutNet",
      "PutBid",
      "PutAsk",
      "PutVol",
      "PutIV",
      "PutDelta",
      "PutGamma",
      "PutOpenInt",
  ]
```

**Comment by rdyvptnm** [comment]
> @rdyvptnm
> 
> By default, the format that `calc.py` looks for is like the examples provided. Without an API, the quickest way to get a CSV file in this format is from the CBOE site.
> 
> ```
>   ---Example Data---
>   Standard & Poors 500 Index,Last: 3990.5601,Change:  56.1801
>   "Date: December 12, 2022 at 8:30 PM EST",Bid: 3962.01,Ask: 4016.6299,Size: 1*1,Volume: 0
>   Expiration Date,Calls,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest,Strike,Puts,Last Sale,Net,Bid,Ask,Volume,IV,Delta,Gamma,Open Interest
>   Mon Dec 12 2022,SPXW221212C01000000,2943.2,0.25,0,0,8,0,0,0,1,1000.00,SPXW221212P01000000,0,0,0,0,0,0,0,0,0
>   ...
> ```
> 
> If you have a different format, you can modify `calc.py` to your preference. The spot price is taken from the 2nd line (1st line is ignored), and the date is taken from the 3rd.
> 
> ```
>   # Get Spot
>   spotLine = optionsFileData[1]
>   spotPrice = float(spotLine.split("Last:")[1].split(",")[0])
>   fromStrike = 0.5 * spotPrice
>   toStrike = 1.5 * spotPrice
>   # Get Today's Date
>   dateLine = optionsFileData[2]
>   todayDate = dateLine.split("Date: ")[1].split(",Bid")[0]
> ```
> 
> The options data is separated in columns starting from the fifth line.
> 
> ```
>   df = pd.read_csv(filename, sep=",", header=None, skiprows=4)
>   df.columns = [
>       "ExpirationDate",
>       "Calls",
>       "CallLastSale",
>       "CallNet",
>       "CallBid",
>       "CallAsk",
>       "CallVol",
>       "CallIV",
>       "CallDelta",
>       "CallGamma",
>       "CallOpenInt",
>       "StrikePrice",
>       "Puts",
>       "PutLastSale",
>       "PutNet",
>       "PutBid",
>       "PutAsk",
>       "PutVol",
>       "PutIV",
>       "PutDelta",
>       "PutGamma",
>       "PutOpenInt",
>   ]
> ```

I am using the same file that is under "data" folder. 
<img width="693" alt="image" src="https://github.com/aaguiar10/gflows/assets/39633746/ed013d63-e0ea-4651-b5c8-1209006234f1">

I commented these 2 lines in my_app.py and  it runs cleanly with out throwing any exceptions  but still no data in the webpage "spx data unavailable try later"

<img width="515" alt="image" src="https://github.com/aaguiar10/gflows/assets/39633746/04517ef2-4601-4ca2-af74-5632dd3c4e63">


<img width="611" alt="image" src="https://github.com/aaguiar10/gflows/assets/39633746/4fdb06aa-715b-4f31-9a4a-a6a1bcea8e4d">

Appreciate looking into this issue

**Comment by rdyvptnm** [comment]
> 

can we hard code some url with some debug log saying this needs to be replaced with your own URL

**Comment by aaguiar10** [comment]
@rdyvptnm,

It should be able to read files in the data directory without any URL.

Can you set debug mode to **True** in `my_app.py`
```
if __name__ == "__main__":
    cache.clear()
    app.run(debug=True)
```
and add these print statements to `calc.py`

```
df = pd.read_csv(filename, sep=",", header=None, skiprows=4)
print("file:", filename)
print("df:", df)
```

I'd like to see this output to get a better idea of your issue.

**Comment by aaguiar10** [comment]
@rdyvptnm,

It should be able to read files in the data directory without any URL.

Can you set debug mode to **True** in `my_app.py`
```
if __name__ == "__main__":
    cache.clear()
    app.run(debug=True)
```
and add these print statements to `calc.py`

```
df = pd.read_csv(filename, sep=",", header=None, skiprows=4)
print("file:", filename)
print("df:", df)
```

It'll help me get a better idea of the issue.

**Comment by rdyvptnm** [comment]
I found the issue.. for some reason the files in data folder were reset and they were empty.  I downloaded todays data from the cboe web site and its working. 

 I have couple questions as a follow up:

1. How do I update this data in real time instead of 15 minutes
2. Do i need to download data every day from the cboe website?
3. Do i need to download monthly data or will it be updated automatically.


<img width="591" alt="image" src="https://github.com/aaguiar10/gflows/assets/39633746/db0d78c9-71ef-4028-96b3-9a78bb4e3cdc">

**Comment by rdyvptnm** [comment]
it looks like for real time data you need the URL. May i know what URL you are using for your website (gflows). is that free version or do i need to pay?

**Comment by aaguiar10** [comment]
@rdyvptnm,

Glad to hear it's working

To answer your questions:

1. Real-time data comes with more costs. You'd have to purchase this from a provider that offers it (if there's enough interest, I'll add real-time data in the future but as a subscription).
2. Unless you provide an API to pull data from, you have to download the CSV files every day from the CBOE site and manually replace the files in the data folder.
3. The data doesn't update automatically without an API.

> it looks like for real time data you need the URL. May i know what URL you are using for your website (gflows). is that free version or do i need to pay?

My API is private.
If you have other questions, please redirect them to the 'Discussions' section
